export default stepProps = [
    {
        id: "1",
        text: "first",
        title: "My First",
        el: "[title='Stop editing sheet']",
        firstAction: "exit",
        lastAction: "next",
        noEl: false,
    },
    {
        id: "2",
        text: "second",
        title: "My Second",
        el: ".MuiIconButton-label",
        firstAction: "back",
        lastAction: "next",
        openAction: false,
    },
    {
        id: "3",
        text: "second",
        title: "My Second",
        el: "[value='isReadFromCacheEnabled']",
        firstAction: "back",
        lastAction: "next",
        openAction: false,
    },
    {
        id: "4",
        text: "second",
        title: "My Second",
        el:
            "button[class='MuiButtonBase-root MuiTab-root MuiTab-textColorInherit']",
        firstAction: "back",
        lastAction: "next",
        openAction: true,
    },
    {
        id: "5",
        text: "second",
        title: "My Second",
        el: "noEl",
        firstAction: "back",
        lastAction: "next",
        openAction: false,
    },
    {
        id: "6",
        text: "second",
        title: "My hhhh",
        el: "[title='Edit']",
        firstAction: "back",
        lastAction: "complete",
        openAction: false,
    },
];
